baseURL: https://vasilyrakche.github.io
languageCode: en-us
title: Vasilije Rakcevic
theme: yourfolio
disableKinds: [RSS, taxonomy]
googleAnalytics: UA-XXXXX-Y

# Menu items
menu:
  main:
  - name: Home
    weight: 1
    url: /
  - name: About
    weight: 2
    url: /about
  - name: Lab@MIRMI
    weight: 2
    url: /lab_mirmi

# Custom params
params:
  env: development
  logoImage: img/v_logo.jpg
  logoImageAlt: Vasilije Rakcevic logo